WIP: unsuccessful attempt to upgrade to google-java-format 1.25.2
This needs JDK 17 or newer, but I can't get it to run locally. I keep
winding up with SDK 11 in spite of setting avrious environment
variables and changing parameters Bazel parameters in this commit.

The error message I get is:

```
❯ bazelisk  run :google_java_format --enable_workspace
…
INFO: Running command line: bazel-bin/google_java_format.sh
openjdk version "11.0.23" 2024-04-16 LTS
OpenJDK Runtime Environment Zulu11.72+19-CA (build 11.0.23+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.72+19-CA (build 11.0.23+9-LTS, mixed mode)
Error: LinkageError occurred while loading main class com.google.googlejavaformat.java.Main
        java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```